server.port: 9090
spring:
  h2:
    console:
      enabled: true
      path: /h2-console        management:  endpoint:    health:      show-details: always
  server:
    port: 9091  endpoints:    web:      exposure:        include: '*'